Repository Yeonba/yeonba-api-server, pull requests merged in 2024-03, with the labels that each got.

#2 Docs/#1 api docs
  be/src/main/java/yeonba/be/arrow/controller/ArrowController.java
  be/src/main/java/yeonba/be/arrow/dto/UserArrowsResponse.java
  be/src/main/java/yeonba/be/chatting/controller/ChattingController.java
  be/src/main/java/yeonba/be/chatting/dto/ChattingRoomResponse.java
  be/src/main/java/yeonba/be/chatting/dto/request/ChattingSendMessageRequest.java
  be/src/main/java/yeonba/be/config/SwaggerConfig.java
  be/src/main/java/yeonba/be/login/controller/LoginController.java
  be/src/main/java/yeonba/be/login/dto/request/UserIdInquiryRequest.java
  be/src/main/java/yeonba/be/login/dto/request/UserJoinRequest.java
  be/src/main/java/yeonba/be/login/dto/request/UserLoginRequest.java
  be/src/main/java/yeonba/be/login/dto/request/UserPasswordInquiryRequest.java
  be/src/main/java/yeonba/be/login/dto/request/UserPhoneNumberVerifyRequest.java
  be/src/main/java/yeonba/be/login/dto/request/UserRefreshTokenRequest.java
  be/src/main/java/yeonba/be/login/dto/response/UserIdInquiryResponse.java
  be/src/main/java/yeonba/be/login/dto/response/UserJoinResponse.java
  be/src/main/java/yeonba/be/login/dto/response/UserLoginResponse.java
  be/src/main/java/yeonba/be/login/dto/response/UserRefreshTokenResponse.java
  be/src/main/java/yeonba/be/mypage/controller/MyPageController.java
  be/src/main/java/yeonba/be/mypage/dto/request/UserAllowNotificationsRequest.java
  be/src/main/java/yeonba/be/mypage/dto/request/UserChangePasswordRequest.java
  be/src/main/java/yeonba/be/mypage/dto/request/UserCheckPasswordMatchRequest.java
  be/src/main/java/yeonba/be/mypage/dto/request/UserDormantRequest.java
  be/src/main/java/yeonba/be/mypage/dto/request/UserUpdateProfileRequest.java
  be/src/main/java/yeonba/be/mypage/dto/request/UserUpdateUnwantedAcquaintanceRequest.java
  be/src/main/java/yeonba/be/mypage/dto/request/UserUpdateUnwantedAcquaintancesRequest.java
  be/src/main/java/yeonba/be/mypage/dto/response/BlockedUserResponse.java
  be/src/main/java/yeonba/be/mypage/dto/response/BlockedUsersResponse.java
  be/src/main/java/yeonba/be/mypage/dto/response/UnwantedAcquaintanceResponse.java
  be/src/main/java/yeonba/be/mypage/dto/response/UnwantedAcquaintancesResponse.java
  be/src/main/java/yeonba/be/mypage/dto/response/UserProfileDetailResponse.java
  be/src/main/java/yeonba/be/mypage/dto/response/UserProfileImageResponse.java
  be/src/main/java/yeonba/be/mypage/dto/response/UserSimpleProfileResponse.java
  be/src/main/java/yeonba/be/term/controller/TermController.java
  be/src/main/java/yeonba/be/term/dto/response/TermDetailResponse.java
  be/src/main/java/yeonba/be/user/controller/UserController.java
  be/src/main/java/yeonba/be/user/dto/request/UserJoinRequest.java
  be/src/main/java/yeonba/be/user/dto/request/UserQueryRequest.java
  be/src/main/java/yeonba/be/user/dto/request/UserReportRequest.java
  be/src/main/java/yeonba/be/user/dto/response/UserJoinResponse.java
  be/src/main/java/yeonba/be/user/dto/response/UserProfileResponse.java
  be/src/main/java/yeonba/be/user/dto/response/UserQueryPageResponse.java
  be/src/main/java/yeonba/be/user/dto/response/UserQueryResponse.java
  be/src/main/java/yeonba/be/util/CustomResponse.java
Labels: :scroll: docs

#4 [템플릿] 이슈, PR 템플릿 생성(#3)
  be/.github/ISSUE_TEMPLATE/default-issue.md
  be/.github/pull_request_template.md
Labels: :scroll: docs

#7 [비밀번호 수정] feat: 엔티티 생성 및 비밀번호 수정 API (#6)
  be/src/main/java/yeonba/be/arrow/entity/ArraowTransaction.java
  be/src/main/java/yeonba/be/config/DevAuthInterceptor.java
  be/src/main/java/yeonba/be/config/GlobalExceptionHandler.java
  be/src/main/java/yeonba/be/config/WebConfig.java
  be/src/main/java/yeonba/be/mypage/controller/MyPageController.java
  be/src/main/java/yeonba/be/mypage/entity/Acquaintance.java
  be/src/main/java/yeonba/be/mypage/entity/Report.java
  be/src/main/java/yeonba/be/mypage/service/MyPageService.java
  be/src/main/java/yeonba/be/term/entity/Term.java
  be/src/main/java/yeonba/be/user/entity/Animal.java
  be/src/main/java/yeonba/be/user/entity/Area.java
  be/src/main/java/yeonba/be/user/entity/Block.java
  be/src/main/java/yeonba/be/user/entity/Favorite.java
  be/src/main/java/yeonba/be/user/entity/ProfilePhoto.java
  be/src/main/java/yeonba/be/user/entity/User.java
  be/src/main/java/yeonba/be/user/entity/UserRecommendation.java
  be/src/main/java/yeonba/be/user/entity/VocalRange.java
  be/src/main/java/yeonba/be/user/repository/UserRepository.java
  be/src/main/java/yeonba/be/user/service/UserService.java
Labels: :sparkles: feat, :cake: chore

#13 [예외 처리] 커스텀 예외 처리 구현(#9)
  be/src/main/java/yeonba/be/exception/ExceptionAdvice.java
  be/src/main/java/yeonba/be/exception/ExceptionType.java
  be/src/main/java/yeonba/be/exception/GeneralException.java
  be/src/main/java/yeonba/be/util/CustomResponse.java
Labels: :sparkles: feat

#11 [내 프로필] 내 프로필 관련 API 생성 및 로직 구성
  be/src/main/java/yeonba/be/config/DevAuthInterceptor.java
  be/src/main/java/yeonba/be/mypage/controller/MyPageController.java
  be/src/main/java/yeonba/be/mypage/dto/request/UserUpdateProfileRequest.java
  be/src/main/java/yeonba/be/mypage/dto/response/UserProfileDetailResponse.java
  be/src/main/java/yeonba/be/mypage/dto/response/UserProfileImageResponse.java
  be/src/main/java/yeonba/be/mypage/dto/response/UserSimpleProfileResponse.java
  be/src/main/java/yeonba/be/mypage/service/MyPageService.java
  be/src/main/java/yeonba/be/user/entity/User.java
Labels: :sparkles: feat

#16 [S3] S3 세팅 초기 설정 및 이미지 업로드 테스트(#15)
  be/build.gradle
  be/src/main/java/yeonba/be/config/S3Config.java
  be/src/main/java/yeonba/be/exception/GeneralException.java
  be/src/main/java/yeonba/be/mypage/controller/MyPageController.java
  be/src/main/java/yeonba/be/mypage/service/MyPageService.java
Labels: :sparkles: feat

#17 [출석 체크] 출석 체크 비즈니스 로직 및 API 구성(#14)
  be/src/main/java/yeonba/be/arrow/controller/ArrowController.java
  be/src/main/java/yeonba/be/arrow/entity/ArrowTransaction.java
  be/src/main/java/yeonba/be/arrow/repository/ArrowTransactionCommandRepository.java
  be/src/main/java/yeonba/be/arrow/service/ArrowService.java
  be/src/main/java/yeonba/be/config/JpaConfig.java
  be/src/main/java/yeonba/be/user/entity/User.java
Labels: :sparkles: feat

#32 [동일 객체 비교 로직 제안] EqualsAndHashCode를 활용해 동일 객체 비교 로직 제안(#31)
  be/src/main/java/yeonba/be/user/entity/User.java
Labels: :sparkles: feat

#21 [내 화살 개수 조회] 내 화살 개수 조회 비즈니스 로직 및 API 구성(#18)
  be/src/main/java/yeonba/be/arrow/controller/ArrowController.java
  be/src/main/java/yeonba/be/arrow/dto/UserArrowsResponse.java
  be/src/main/java/yeonba/be/arrow/repository/ArrowCommand.java
  be/src/main/java/yeonba/be/arrow/repository/ArrowTransactionRepository.java
  be/src/main/java/yeonba/be/arrow/service/ArrowService.java
  be/src/main/java/yeonba/be/config/DevAuthInterceptor.java
  be/src/main/java/yeonba/be/exception/ArrowException.java
  be/src/main/java/yeonba/be/mypage/service/MyPageService.java
  be/src/main/java/yeonba/be/mypage/service/ReportService.java
  be/src/main/java/yeonba/be/user/entity/User.java
  be/src/main/java/yeonba/be/user/repository/UserQuery.java
  be/src/main/java/yeonba/be/user/repository/UserRepository.java
  be/src/main/java/yeonba/be/user/service/UserService.java
Labels: :sparkles: feat

#23 [차단하기] 차단하기 비즈니스 로직 및 API 구성(#22)
  be/src/main/java/yeonba/be/exception/BlockException.java
  be/src/main/java/yeonba/be/user/controller/UserController.java
  be/src/main/java/yeonba/be/user/entity/Block.java
  be/src/main/java/yeonba/be/user/repository/BlockCommand.java
  be/src/main/java/yeonba/be/user/repository/BlockQuery.java
  be/src/main/java/yeonba/be/user/repository/BlockRepository.java
  be/src/main/java/yeonba/be/user/service/BlockService.java
Labels: :sparkles: feat

#25 [화살 보내기] 화살 보내기 비즈니스 로직 및 API 구성(#24)
  be/src/main/java/yeonba/be/arrow/controller/ArrowController.java
  be/src/main/java/yeonba/be/arrow/dto/request/ArrowSendRequest.java
  be/src/main/java/yeonba/be/arrow/entity/ArrowTransaction.java
  be/src/main/java/yeonba/be/arrow/repository/ArrowQuery.java
  be/src/main/java/yeonba/be/arrow/repository/ArrowTransactionRepository.java
  be/src/main/java/yeonba/be/arrow/service/ArrowService.java
  be/src/main/java/yeonba/be/exception/ArrowException.java
  be/src/main/java/yeonba/be/user/entity/User.java
Labels: :sparkles: feat

#39 [마이페이지] 비밀번호 수정 로직 추가, 일부 엔티티 변경
  be/src/main/java/yeonba/be/exception/ExceptionAdvice.java
  be/src/main/java/yeonba/be/mypage/controller/MyPageController.java
  be/src/main/java/yeonba/be/mypage/dto/response/UserProfileDetailResponse.java
  be/src/main/java/yeonba/be/mypage/service/MyPageService.java
  be/src/main/java/yeonba/be/mypage/util/PasswordEncryptor.java
  be/src/main/java/yeonba/be/user/entity/User.java
Labels: :sparkles: feat

#33 [즐겨찾기 등록] 즐겨찾기 등록 비즈니스 로직 및 API 구성(#26)
  be/src/main/java/yeonba/be/exception/FavoriteException.java
  be/src/main/java/yeonba/be/user/controller/UserController.java
  be/src/main/java/yeonba/be/user/entity/Favorite.java
  be/src/main/java/yeonba/be/user/repository/favorite/FavoriteCommand.java
  be/src/main/java/yeonba/be/user/repository/favorite/FavoriteQuery.java
  be/src/main/java/yeonba/be/user/repository/favorite/FavoriteRepository.java
  be/src/main/java/yeonba/be/user/service/FavoriteService.java
Labels: :sparkles: feat

#36 [상대 프로필 조회] 상대 프로필 조회 비즈니스 로직 및 API 구성(#27)
  be/src/main/java/yeonba/be/exception/ExceptionAdvice.java
  be/src/main/java/yeonba/be/mypage/dto/response/UserProfileDetailResponse.java
  be/src/main/java/yeonba/be/user/controller/UserController.java
  be/src/main/java/yeonba/be/user/dto/response/UserProfileResponse.java
  be/src/main/java/yeonba/be/user/entity/Animal.java
  be/src/main/java/yeonba/be/user/entity/User.java
  be/src/main/java/yeonba/be/user/service/UserService.java
Labels: :sparkles: feat

#37 [즐겨찾기 삭제] 즐겨찾기 삭제 비즈니스 로직 및 API 구성(#34)
  be/src/main/java/yeonba/be/exception/FavoriteException.java
  be/src/main/java/yeonba/be/user/controller/UserController.java
  be/src/main/java/yeonba/be/user/entity/User.java
  be/src/main/java/yeonba/be/user/repository/favorite/FavoriteCommand.java
  be/src/main/java/yeonba/be/user/repository/favorite/FavoriteQuery.java
  be/src/main/java/yeonba/be/user/repository/favorite/FavoriteRepository.java
  be/src/main/java/yeonba/be/user/service/FavoriteService.java
Labels: :sparkles: feat

#47 [화살 충전] 광고 시청을 통한 화살 충전
  be/build.gradle
  be/src/main/java/yeonba/be/arrow/controller/ArrowController.java
  be/src/main/java/yeonba/be/arrow/entity/ArrowTransaction.java
  be/src/main/java/yeonba/be/arrow/repository/ArrowQuery.java
  be/src/main/java/yeonba/be/arrow/repository/ArrowTransactionRepository.java
  be/src/main/java/yeonba/be/arrow/repository/ArrowTransactionRepositoryCustom.java
  be/src/main/java/yeonba/be/arrow/repository/ArrowTransactionRepositoryImpl.java
  be/src/main/java/yeonba/be/arrow/service/ArrowService.java
  be/src/main/java/yeonba/be/config/QueryDslConfig.java
  be/src/main/java/yeonba/be/exception/ArrowException.java
  be/src/main/java/yeonba/be/user/repository/UserQuery.java
  be/src/main/java/yeonba/be/user/repository/UserRepository.java
Labels: :sparkles: feat

#45 [설정 페이지] 설정 페이지 일부 구현
  be/src/main/java/yeonba/be/BeApplication.java
  be/src/main/java/yeonba/be/config/ScheduleConfig.java
  be/src/main/java/yeonba/be/exception/BlockException.java
  be/src/main/java/yeonba/be/mypage/controller/MyPageController.java
  be/src/main/java/yeonba/be/mypage/dto/response/BlockedUserResponse.java
  be/src/main/java/yeonba/be/mypage/dto/response/BlockedUsersResponse.java
  be/src/main/java/yeonba/be/mypage/service/MyPageService.java
  be/src/main/java/yeonba/be/user/entity/User.java
  be/src/main/java/yeonba/be/user/repository/BlockCommand.java
  be/src/main/java/yeonba/be/user/repository/BlockQuery.java
  be/src/main/java/yeonba/be/user/repository/BlockRepository.java
  be/src/main/java/yeonba/be/user/repository/UserQuery.java
  be/src/main/java/yeonba/be/user/repository/UserRepository.java
Labels: :sparkles: feat

#41 [인증 코드 sms 전송, 이메일 찾기] 인증 코드 sms 전송 & 이메일 찾기 비즈니스 로직 및 API 구현(#28)
  be/build.gradle
  be/src/main/java/yeonba/be/config/SmsConfig.java
  be/src/main/java/yeonba/be/exception/LoginException.java
  be/src/main/java/yeonba/be/login/controller/LoginController.java
  be/src/main/java/yeonba/be/login/dto/request/UserEmailInquiryRequest.java
  be/src/main/java/yeonba/be/login/dto/request/UserIdInquiryRequest.java
  be/src/main/java/yeonba/be/login/dto/request/UserPhoneNumberVerifyRequest.java
  be/src/main/java/yeonba/be/login/dto/request/UserVerificationCodeRequest.java
  be/src/main/java/yeonba/be/login/dto/response/UserEmailInquiryResponse.java
  be/src/main/java/yeonba/be/login/entity/VerificationCode.java
  be/src/main/java/yeonba/be/login/repository/VerificationCodeCommand.java
  be/src/main/java/yeonba/be/login/repository/VerificationCodeQuery.java
  be/src/main/java/yeonba/be/login/repository/VerificationCodeRepository.java
  be/src/main/java/yeonba/be/login/service/LoginService.java
  be/src/main/java/yeonba/be/user/repository/UserQuery.java
  be/src/main/java/yeonba/be/user/repository/UserRepository.java
  be/src/main/java/yeonba/be/util/ServiceRegex.java
  be/src/main/java/yeonba/be/util/SmsService.java
  be/src/main/java/yeonba/be/util/VerificationCodeGenerator.java
Labels: :sparkles: feat
